### ISSUE TITLE
Typo in template code: 'initiatlized'

### ISSUE THREAD

**Issue by lanzone1** [tagconcierge/tagconcierge-gtm-cookies-template#1]
When reviewing your template, we noticed a likely bug.
```
if (null === templateStorage.getItem('initiatlized')) {
```
Note the extra `t` in `initialized`. This check will always be true.

**Comment by michaloo** [comment]
Thanks for pointing it out, fixed in https://github.com/tagconcierge/tagconcierge-gtm-cookies-template/commit/a98bcc2f4d903b001d330812401537e3806abcf9#diff-dfeab1de57b435942d72fd2eef60b735ad864ee7b35692d09d05d0536ffce292R237
