### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by lanzone1** [tagconcierge/tagconcierge-gtm-cookies-template#2]
When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by michaloo** [comment]
Added this parameter in same commit as the other fixes: https://github.com/tagconcierge/tagconcierge-gtm-cookies-template/commit/a98bcc2f4d903b001d330812401537e3806abcf9#diff-dfeab1de57b435942d72fd2eef60b735ad864ee7b35692d09d05d0536ffce292R343

But it may be a good occasion to ask how does this work when using an async consent tools. Does this needs to be set inline before gtag or dataLayer initialization? I guess if 'setDefaultConsentState' is called by async tool then it would be already "too late" to define such delay, did I miss something?

**Comment by lanzone1** [comment]
`wait_for_update` tells the container to wait *n* ms before sending data. It's basically a way to tell the container, "Hey, we know a CMP is loading, so give it a chance to load and call `gtag('consent', 'update', ...)` before doing too much."
