### ISSUE TITLE
Include all required consent types

### ISSUE THREAD

**Issue by lanzone1** [tagconcierge/tagconcierge-gtm-cookies-template#3]
When reviewing your template, we've noticed that some [required consent types](https://support.google.com/tagmanager/answer/13802165) are missing from the consent commands. Please ensure that your template sets the following consent types:
* `ad_storage`
* `ad_user_data`
* `ad_personalization`
* `analytics_storage`

**Comment by michaloo** [comment]
First, thanks for reviewing our template @lanzone1!
I have added the missing consent types in this commit: https://github.com/tagconcierge/tagconcierge-gtm-cookies-template/commit/a98bcc2f4d903b001d330812401537e3806abcf9

Final list extends the one from your message with `functionality`, `personalization` and `security` privacy parameters, would that work?

**Comment by lanzone1** [comment]
Yep, that works.

Can you also update the `sha` value in [metadata.yaml](https://github.com/tagconcierge/tagconcierge-gtm-cookies-template/blob/main/metadata.yaml) to match? It should be `a98bcc2f4d903b001d330812401537e3806abcf9`.

**Comment by michaloo** [comment]
Thanks! Updated here: https://github.com/tagconcierge/tagconcierge-gtm-cookies-template/commit/8e16fa373199424c1b8ae91424adcb01925912b0
